spring.application.name=ManagedHospital
spring.datasource.url=${DB_URL}
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
server.servlet.context-path=/indra


#Spring-config
spring.profiles.active=prod
spring.security.user.name=Indra
spring.security.user.password=pass


#spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github
jwt.secretKey=${JWT_SECRET}