#applicatio use to define properties like application.properties but this is more user friendly

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${Google_Client_ID}
            client-secret: ${Google_client_Secret}
          github:
            client-id: ${GitHub_Client_ID}
            client-secret: ${GitHub_Client_Secret}
